on: 
  push:
    tags:
      - "v*"

jobs:
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export Software
    steps:
    - name: Get key
      env:
        GIT_NAME: PJ-568
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        REPO: github.com/PJ-568/568_Calc_keystore
        GH_TOKEN: ${{ secrets.TOKEN }}
      run: |
          git config --global user.name $GIT_NAME
          git config --global user.email $GIT_EMAIL
          echo '创建 tmp/：'
          mkdir /home/runner/tmp
          echo '克隆 keystore：'
          git clone https://$GH_TOKEN@$REPO /home/runner/tmp/key

    - name: checkout
      uses: actions/checkout@v3.3.0

    - name: Move key
      run: |
          echo '创建 key/：'
          mkdir ./key
          echo '复制 keystore：'
          cp -u -r /home/runner/tmp/key/* ./key/

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: install wine
      id: wine_install
      run: |
        sudo apt install wine64
        echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT

    - name: export software
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v5.2.1
      with:
        # Defining all the required inputs 
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}

    - name: create release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.TOKEN }}
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: Release/*